server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - path=/user/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - path=/bike/**
